language: php

php:
  - 5.4
  - 5.5

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer install

script:
  - phpcs --ignore=/vendor/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

notifications:
  email: "nbastien@prestaconcept.net"
